### ISSUE TITLE
Communication error with RemedyBG

### ISSUE THREAD

**Issue by bousquetm** [slynch8/10x#2387]
Every time I launch RemedyBg from the python script, I get this error in the 10x Output window:

```[python] Traceback (most recent call last):
[python]   File "C:/Users/Martin/AppData/Roaming/10x/PythonScripts/RemedyBG.py", line 1053, in _RDBG_Update
[python]     if not gSession.update():
[python]   File "C:/Users/Martin/AppData/Roaming/10x/PythonScripts/RemedyBG.py", line 808, in update
[python]     text = event_buffer.read(int.from_bytes(event_buffer.read(2), 'little')).decode('utf-8')
[python] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 27: invalid continuation byte
Error: Callback function failed. Removing callback: <function _RDBG_Update at 0x0000026FB19AC430>
```

After that, RemedyBG is launched correctly but then I can't ever relaunch again from 10x, breakpoints are not synchronized, and so on.

So, 0xe9 is the Latin ISO-8859-1 character for 'é', which I use sometimes in my my source code (in wide string literals), but it's weird because the source files are supposed to be encoded in utf-8, as 10x show in the lower right corner of the window. Even after changing all my 'é' to 'e' for testing purpose (and other characters like 'ê', the error is still there. There must be a file somewhere that has either a bad encoding (not utf-8) or that 10x thinks has bad encoding.

Any idea?

**Comment by slynch8** [comment]
It sound to me like the python script is getting bad data from remedybg and failing to decode it. Are you on the latest version of remedybg and the latest script?

**Comment by bousquetm** [comment]
I have the latest I think:
10x 1.0.123
RemedyBG 0.3.9.7
Python script 0.11.2

**Comment by slynch8** [comment]
I'm not sure if this bug is a bug in the python script or in remedybg. I suspect what might be happening is that remedybg is not handling utf-8 in the DEBUG_OUTPUT_STRING event and the python script is getting a malformed string.

I've asked on the remedybg discord channel.

**Comment by bousquetm** [comment]
Thank you, we'll see on the discord indeed.

**Comment by bousquetm** [comment]
For the record, I found what line causes the isse: at the boot of the game, I call DirectSoundEnumerate with a callback that prints the list of all audio devices. Since my windows is in French, the default audio device is listed as "Périphérique audio principal". Now the weird part is that this string (which is of type LPCTSTR) is encoded in Latin extended ISO8859-1, so 'é' is encoded as 0xe9... Printing this string with printf will cause the error in the Python script.
